{{- if .Values.services.consultSubAgent.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consult-sub-agent
  namespace: {{ .Values.global.namespace }}
  labels:
    app: consult-sub-agent
spec:
  replicas: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      app: consult-sub-agent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: consult-sub-agent
    spec:
      initContainers:
        {{- include "agentscope.waitForNacos" . | nindent 8 }}
      containers:
        - name: consult-sub-agent
          image: {{ .Values.image.registry }}/consult-sub-agent:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 10005
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "10005"
            {{- include "agentscope.commonEnv" . | nindent 12 }}
          resources:
            requests:
              cpu: "1"
              memory: 2048Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
{{- end }}
